---
postgresql_packages:
  - "postgresql{{ postgresql_version }}-server"
  - "postgresql{{ postgresql_version }}-contrib"
  - "postgresql{{ postgresql_version }}"
  - glibc-langpack-en          # provides the en_US.UTF-8 locale for initdb
postgresql_service_name: "postgresql-{{ postgresql_version }}"
