---
- name: Restart chrony
  ansible.builtin.service:
    name: "{{ (ansible_os_family == 'Debian') | ternary('chrony', 'chronyd') }}"
    state: restarted

- name: Restart cron
  ansible.builtin.service:
    name: "{{ (ansible_os_family == 'Debian') | ternary('cron', 'crond') }}"
    state: restarted
